apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: jenkins
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "10Mi"
            cpu: "50m"
          limits:
            memory: "50Mi"
            cpu: "100m"
      restartPolicy: Always
      dnsPolicy: ClusterFirst
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-autoscaler
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  targetCPUUtilizationPercentage: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: jenkins
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: jenkins
spec:
  tls:
  - hosts:
    - nginx.k8s.globalitfactory.eu
    secretName: nginx-secret-tls
  rules:
  - host: nginx.k8s.globalitfactory.eu
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret-tls
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZQekNDQkNlZ0F3SUJBZ0lTQkRhWVBTQ2c3NUhMR3pBN3duNjJKU0RJTUEwR0NTcUdTSWIzRFFFQkN3VUEKTURJeEN6QUpCZ05WQkFZVEFsVlRNUll3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1Rc3dDUVlEVlFRRApFd0pTTXpBZUZ3MHlNREV5TWpreE1qRXlNVGhhRncweU1UQXpNamt4TWpFeU1UaGFNQ2N4SlRBakJnTlZCQU1UCkhHNW5hVzU0TG1zNGN5NW5iRzlpWVd4cGRHWmhZM1J2Y25rdVpYVXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUEKQTRJQkR3QXdnZ0VLQW9JQkFRQ203SDJZZ1RzNFh6amk3bC92azdOR20yY1VVdWpwME45YWtIV1cvc0w5ZHVUbQpVenVySnN3MXJwaUNwS3FtZFJFUjBmMVpKdHVValVtTmdhdjUyakQxbE00b2p2UEJabkxlc1prdkY4VTNEWUdpCkFubVhuMG51ZVljbkI3SzZ3YXd0d0FPNzBGc0U2VFhuSCtZZnFKTUI1S2dyL1loRnJNVEpsSlQzYWswQVIwRU0KTm5iNjBWby82Y2FjeHFPSHl6YzBwbzNNZjhnaWFIUHFsQS8vMTBRNE5ESlB3UHZBTi9WTFp2YkJCTE9TZjFRQwpoVDNKa2hUdC9UMitZVHZKaE85Rkpqc2xBc0dJTjN6dWJDdThLQXlEckkrUkpkZllDdGg0NnJvVXZnbmlpYTVMCnNFQzF6SlBXeVZzZk9pZFZqMlNVNnZxQ3AzaFgvRGxDRDVrbDRBb2xBZ01CQUFHamdnSllNSUlDVkRBT0JnTlYKSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQXdHQTFVZApFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUVGSnZaUEovVFZmaExLMXZOazFhTWlSb0U0MDJLTUI4R0ExVWRJd1FZCk1CYUFGQlF1c3hlM1dGYkxybEFKUU9ZZnI1MkxGTUxHTUZVR0NDc0dBUVVGQndFQkJFa3dSekFoQmdnckJnRUYKQlFjd0FZWVZhSFIwY0RvdkwzSXpMbTh1YkdWdVkzSXViM0puTUNJR0NDc0dBUVVGQnpBQ2hoWm9kSFJ3T2k4dgpjak11YVM1c1pXNWpjaTV2Y21jdk1DY0dBMVVkRVFRZ01CNkNIRzVuYVc1NExtczRjeTVuYkc5aVlXeHBkR1poClkzUnZjbmt1WlhVd1RBWURWUjBnQkVVd1F6QUlCZ1puZ1F3QkFnRXdOd1lMS3dZQkJBR0MzeE1CQVFFd0tEQW0KQmdnckJnRUZCUWNDQVJZYWFIUjBjRG92TDJOd2N5NXNaWFJ6Wlc1amNubHdkQzV2Y21jd2dnRUZCZ29yQmdFRQpBZFo1QWdRQ0JJSDJCSUh6QVBFQWRnRDJYSlF2MFhjd0loUlVHQWd3bEZhTzQwMFRHVE8vM3d3dklBdk1UdkZrCjR3QUFBWGF1b0wxTUFBQUVBd0JITUVVQ0lRQzRFcERzenZJYkd2bjI0R3lZVm5Kemx0ditmYm4zdDFvT0sxR0IKbG44VzV3SWdFM0sxSHpGZjlya2w5eEU2SzBkRmJrbDV4NzBVVHMxWU13MDVzQnoyYUw4QWR3QnZVM2FzTWZBeApHZGlaQUtSUkZmOTNGUndSMlFMQkFDa0dqYklJbWpmWkV3QUFBWGF1b0wxNEFBQUVBd0JJTUVZQ0lRRHlEZzRFCmlwZjMzNXZWUHQ4d29qMWNEOGYyYldadkFHbTI5R2NDS2ppRml3SWhBTFAxVWJXdXA2OFVjay9saUZjOHFwaXUKN2o5T3kyd3JQMW5rZXBuVHVYSVJNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJ6SzRuYXRYamluNkdtT0lDZApTMzc5Mis0REN6K3l6MU5XRnBMRnVFYll3UGVsUzRReVAwUzg1R1BkWmljTW9TbUNnZVZtNjUzSlBEY1RzcWJvCjl6Ty82TDhZR1YvQnNoYjlvakhFM25MdURhQ2t0eHAwK1NyVUpZYndCck9YZHBQM3pacXVHbzVLSFRGcDZxckMKOW1XQlJab0R0TnJQMThuSVN1OExNSzlldzZQS3lmOS80VkI1NDNNM1E3NlRMZUFnN2JPeXQvZFFsWW9IdmFSZwovaUJ0OWo2bWdmdm9kKzgwVjZHRm1XVmpmWWVocDhRZzc2R3hkWlRrK2JFaDd1SDN6NzVFMnl3N2lNUWxQMXJQClU3ZWU3RmlGL2xVQjUyYnJjcjRqQkIzeXNFN1FaYWw0TXh4OXgxZGhBMlpORFU1d3pBYTc1cC9KcVIzeURXbmIKMVVOdQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlFWlRDQ0EwMmdBd0lCQWdJUVFBRjFCSU1VcE1naGpJU3BEQmJOM3pBTkJna3Foa2lHOXcwQkFRc0ZBREEvCk1TUXdJZ1lEVlFRS0V4dEVhV2RwZEdGc0lGTnBaMjVoZEhWeVpTQlVjblZ6ZENCRGJ5NHhGekFWQmdOVkJBTVQKRGtSVFZDQlNiMjkwSUVOQklGZ3pNQjRYRFRJd01UQXdOekU1TWpFME1Gb1hEVEl4TURreU9URTVNakUwTUZvdwpNakVMTUFrR0ExVUVCaE1DVlZNeEZqQVVCZ05WQkFvVERVeGxkQ2R6SUVWdVkzSjVjSFF4Q3pBSkJnTlZCQU1UCkFsSXpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXV3SVZLTXoyb0pUVER4THMKalZXU3cvaUM4Wm1tZWtLSXAxMG1xclVydWNWTXNhK09hL2wxeUtQWEQwZVVGRlUxVjR5ZXFLSTVHZldDUEVLcApUbTcxTzhNdTI0M0FzRnp6V1RqbjdjOXA4Rm9MRzc3QWxDUWxoL28zY2JNVDV4eXM0WnZ2MitRN1JWSkZscW5CClU4NDB5Rkx1dGE3dGo5NWdjT0tsVkt1MmJRNlhwVUEwYXl2VHZHYnJaalI4K211TGoxY3BtZmd3RjEyNmNtLzcKZ2NXdDBvWllQUmZINXdtNzhTdjNodHpCMm5GZDFFYmp6SzBsd1lpOFlHZDFaclB4R1BlaVhPWlQvenFJdGtlbAoveE1ZNnBnSmR6K2RVL25QQWVYMXBuQVhGSzlqcFArWnM1T2QzRk9uQnY1SWhSMmhhYTRsZGJzVHpGSUQ5ZTFSCm9ZdmJGUUlEQVFBQm80SUJhRENDQVdRd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFEQU9CZ05WSFE4QkFmOEUKQkFNQ0FZWXdTd1lJS3dZQkJRVUhBUUVFUHpBOU1Ec0dDQ3NHQVFVRkJ6QUNoaTlvZEhSd09pOHZZWEJ3Y3k1cApaR1Z1ZEhKMWMzUXVZMjl0TDNKdmIzUnpMMlJ6ZEhKdmIzUmpZWGd6TG5BM1l6QWZCZ05WSFNNRUdEQVdnQlRFCnA3R2tleXh4K3R2aFM1QjEvOFFWWUlXSkVEQlVCZ05WSFNBRVRUQkxNQWdHQm1lQkRBRUNBVEEvQmdzckJnRUUKQVlMZkV3RUJBVEF3TUM0R0NDc0dBUVVGQndJQkZpSm9kSFJ3T2k4dlkzQnpMbkp2YjNRdGVERXViR1YwYzJWdQpZM0o1Y0hRdWIzSm5NRHdHQTFVZEh3UTFNRE13TWFBdm9DMkdLMmgwZEhBNkx5OWpjbXd1YVdSbGJuUnlkWE4wCkxtTnZiUzlFVTFSU1QwOVVRMEZZTTBOU1RDNWpjbXd3SFFZRFZSME9CQllFRkJRdXN4ZTNXRmJMcmxBSlFPWWYKcjUyTEZNTEdNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUEyVXpneWZXRWlEY3gyN3NUNHJQOGkydGlFbXhZdDBsK1BBSzNxQjhvWWV2TzRDNXo3MGtICmVqV0VIeDJ0YVBEWS9sYUJMMjEvV0tadU5UWVFISFBENWIxdFhnSFhibkw3S3FDNDAxZGs1VnZDYWRUUXN2ZDgKUzhNWGpvaHljOXo5L0cyOTQ4a0xqbUU2RmxoOWREWXJWWUE5eDJPK2hFUEdPYUVPYTFlZVB5bkJnUGF5dlVmTApxakJzdHpMaFdWUUxHQWtYWG1Ocys1Wm5QQnh6REpPTHhoRjJKSWJlUUFjSDVIMHRaclVsbzVaWXlPcUE3czlwCk81Yjg1bzNBTS9PSitDa3RGQlF0ZnZCaGNKVmQ5d3Zsd1Bzayt1eU95MkhJN21OeEtLZ3NCVHQzNzV0ZUEyVHcKVWRIa2hWTmNzQUtYMUg3R05OTE9FQURrc2Q4Nnd1b1h2Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBcHV4OW1JRTdPRjg0NHU1Zjc1T3pScHRuRkZMbzZkRGZXcEIxbHY3Qy9YYms1bE03CnF5Yk1OYTZZZ3FTcXBuVVJFZEg5V1NiYmxJMUpqWUdyK2RvdzlaVE9LSTd6d1daeTNyR1pMeGZGTncyQm9nSjUKbDU5SjdubUhKd2V5dXNHc0xjQUR1OUJiQk9rMTV4L21INmlUQWVTb0svMklSYXpFeVpTVTkycE5BRWRCRERaMgordEZhUCtuR25NYWpoOHMzTkthTnpIL0lJbWh6NnBRUC85ZEVPRFF5VDhEN3dEZjFTMmIyd1FTemtuOVVBb1U5CnlaSVU3ZjA5dm1FN3lZVHZSU1k3SlFMQmlEZDg3bXdydkNnTWc2eVBrU1hYMkFyWWVPcTZGTDRKNG9tdVM3QkEKdGN5VDFzbGJIem9uVlk5a2xPcjZncWQ0Vi93NVFnK1pKZUFLSlFJREFRQUJBb0lCQVFDQlJNbnJEY0dQNFdaTApqN0VwOXVjeU9lejA5MVE2cHJBaUVaZVBETkp5dWQyQVpWcmpLNU9meXd0K3VRa1RDYnZqWWd6aU9zNTMxNGJyCm1FMVhtOXFvaE1tMjdTWG1VM0dIOWwrYjhidWY2OHpGYTBkQTNYSEN4Y2lkdUQ5NGs3M0VYRnhIMlk1eldpdU4KUnMzUEhKeGtMZkR5eUUvOUxWUGtqRFZrK2FTU0hsd1Brb2NhUHVya1pvK0pEdDI4cndKV2o5ZVpubFp1bSs1MQpydEFXYnRuSm9sM3dyTmlGSjdOc3lJMjFNQmRyMUpzdW9Nc0JiRWxTU1p5OTFZbnlWSlRSUEdEaW15ajVhc2kxCmxoZEJCLzZrOTNReUtxeHhTckZIVWc1VjRHZGlGaGcvckJqblZjYUt3SzFPTFY1bWM2SzNCeHZaWHNoRUxlTG4KTTlaM3Y3d2hBb0dCQU10RitZS2p6MVNTQ0lkWE9GS2xiUGEzcGNTNDhEdHlmVXdLTzV3R1NmaDNDZnZEbEd6SAoveDJoMlowaFhEVUhocXJGMnEzUkpzUUxPY1Q3bUN1SW1YOTc3VUp2OUtYd1NFU2pxTk5takZhRmNPVG0yMC81CnUxNUZNRUl6aDFQRks4Ny9Ic1NxZEhHdjN4aStGNFFuTnExY1ZMWmlwSG5lclpmcVpUNUYrM09aQW9HQkFOSTQKeVFPTWZWNU5KSjdrdCs0bmtFUzZPZ2VIZzJ4bWk5SzRSam1iNk9KcGxhSU9Va1dSbkM2TEhJcnpXdHA1MGt2TApoZ3BWSkdzVG12VTNGdUpObG04T09WYlFYUUR4WkVRZzUxTXhwSnczNERaZ2VPbWgwUStTTVFFLzExWmhwODVhCk1NUnNqMEtqVXp4SmR4eXV4Y2cyQjlGdWF3WXFqSDFwejJacGthSnRBb0dBV3NhMkJWeElFNWxmaTZrc3N1UEQKUkc2QTdkZzFHQ2NwdzFKeWlsdlluc2Z5UW1kMkdobzZXSzVWc3pFWnIyamIvOWw1cmRQUVB3NVFUeUtZTXlDKwpnOHNCQ29GYXZOd1FPZTdvVHZmbHhpR3paOVdjclJ0MlRFUVRxQXpBNjIwTEFsYTJFOWVYUnNubWxITVhwMkduCnJrV2tZd3FzTHV4OWszRU9vMyszS2trQ2dZQitUai80TWVEaFY5ZzQzNUxqTkVJcUNQbjByQ2I2YW1KNEtOK0kKblhRL0ZORWluUmd4VkZ0U1c2SzZtWnhzeCtUaVJWWXp2eFF5Z1lVSThDQi90NzQ2MjREMytCanBDQ0FHRHY3dApyVllKeGtpZ1l6WkNxVWJDNUVNdFRQNUVtRWdLWTRZSmZuQlV5V3lwUERxa3NSMkVQWEpWRXRLYTBkVzNSR3VvClRLV0R3UUtCZ1FDU0I4Unh6dHgydW1CK25hYXhSNFM0TXdLdmpDUGpMaUtZRjBvcmJLMUs1U1pBSVQ3S1J3YTcKQzlvRk5lNFdZVW9IWDA1ZEd3c09McVNEU05oNkZYR3V2TlBJU3pLSmZyTGkwVG93cnViREZ2a2dEV2FDN0ltZQpkdkVFaDZTbjFPMThkQ2J5anZCQ2VZeUtxYXppUmM3MXZEOGY3R0dRdnp3YzNGYisyWjNXaWc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
